name: windows

on:
  push:
    branches: [ master ]
    tags:
      - "v*"

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up build variables
        run: bash ./.github/scripts/setup_build_variables.sh

      - name: Set up windows build variables
        run: bash ./.github/scripts/windows/setup_windows_build_variables.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          install-deps: 'true'
          arch: 'win64_msvc2019_64'

      - name: Set up nmake
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up kColorPicker
        run: bash ./.github/scripts/setup_kColorPicker.sh

      - name: Set up kImageAnnotator
        run: bash ./.github/scripts/setup_kImageAnnotator.sh

      - name: Set up GoogleTest
        run: bash ./.github/scripts/setup_googleTest.sh

      - name: Add GoogleTest bin dir to PATH
        uses: myci-actions/export-env-var@1
        with:
          name: PATH
          value: $PATH:$INSTALL_PREFIX/bin

      - name: Build
        env:
          BUILD_TESTS: ON
        run: bash ./.github/scripts/build_ksnip.sh

      - name: Test
        working-directory: ${{github.workspace}}/build/tests
        run: ctest CTEST_OUTPUT_ON_FAILURE=1


  package-exe:
    runs-on: windows-latest
    needs: test-windows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up build variables
      run: bash ./.github/scripts/setup_build_variables.sh

    - name: Set up windows build variables
      run: bash ./.github/scripts/windows/setup_windows_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        install-deps: 'true'
        arch: 'win64_msvc2019_64'

    - name: Set up nmake
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up kColorPicker
      run: bash ./.github/scripts/setup_kColorPicker.sh
        
    - name: Set up kImageAnnotator
      run: bash ./.github/scripts/setup_kImageAnnotator.sh

    - name: Build
      run: bash ./.github/scripts/build_ksnip.sh

    - name: Download OpenSSL
      run: |
        curl "https://indy.fulgan.com/SSL/openssl-1.0.2q-i386-win32.zip" --output openssl.zip
        7z x openssl.zip -o"${{ env.OPENSSL_DIR }}" || true

    - name: Package exe
      run: bash ./.github/scripts/windows/package_exe.sh

    - name: Upload files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -L https://github.com/probonopd/uploadtool/raw/master/upload.sh --output upload.sh
        bash upload.sh ksnip-*.zip


  package-msi:
    runs-on: windows-latest
    needs: test-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up build variables
        run: bash ./.github/scripts/setup_build_variables.sh

      - name: Set up windows build variables
        run: bash ./.github/scripts/windows/setup_windows_build_variables.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          install-deps: 'true'
          arch: 'win64_msvc2019_64'

      - name: Set up nmake
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up kColorPicker
        run: bash ./.github/scripts/setup_kColorPicker.sh

      - name: Set up kImageAnnotator
        run: bash ./.github/scripts/setup_kImageAnnotator.sh

      - name: Download OpenSSL
        run: |
          curl "https://indy.fulgan.com/SSL/openssl-1.0.2q-i386-win32.zip" --output openssl.zip
          7z x openssl.zip -o"${{ env.OPENSSL_DIR }}" || true

      - name: Build
        run: bash ./.github/scripts/build_ksnip.sh

      - name: Package msi
        run: bash ./.github/scripts/windows/msi/package_msi.sh

      - name: Sign msi
        env:
          MICROSOFT_CERT_PFX: ${{ secrets.MICROSOFT_CERT_PFX }}
          MICROSOFT_CERT_PFX_PASS: ${{ secrets.MICROSOFT_CERT_PFX_PASS }}
        run: powershell ./.github/scripts/windows/msi/sign_msi_package.ps1

      - name: Upload files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L https://github.com/probonopd/uploadtool/raw/master/upload.sh --output upload.sh
          bash upload.sh ksnip-*.msi
