name: windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up build variables
        run: bash ./.github/scripts/setup_build_variables.sh

      - name: Set up windows build variables
        run: bash ./.github/scripts/windows/setup_windows_build_variables.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          install-deps: 'true'
          arch: 'win64_msvc2019_64'

      - name: Set up nmake
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up kColorPicker
        env:
          BUILD_TYPE: Debug
        run: bash ./.github/scripts/setup_kColorPicker.sh

      - name: Set up kImageAnnotator
        env:
          BUILD_TYPE: Debug
        run: bash ./.github/scripts/setup_kImageAnnotator.sh

      - name: Set up GoogleTest
        run: bash ./.github/scripts/setup_googleTest.sh

      - name: Add GoogleTest bin dir to PATH
        uses: myci-actions/export-env-var-powershell@1
        with:
          name: PATH
          value: $env:PATH;$env:INSTALL_PREFIX/bin

      - name: Build
        env:
          BUILD_TESTS: ON
          BUILD_TYPE: Debug
        run: bash ./.github/scripts/build_ksnip.sh

      - name: Test
        working-directory: ${{github.workspace}}/build/tests
        run: ctest --extra-verbose


  package-exe:
    if: ${{ github.event_name == 'push' }}
    runs-on: windows-latest
    needs: test-windows
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up build variables
      run: bash ./.github/scripts/setup_build_variables.sh

    - name: Set up windows build variables
      run: bash ./.github/scripts/windows/setup_windows_build_variables.sh

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        host: 'windows'
        install-deps: 'true'
        arch: 'win64_msvc2019_64'

    - name: Set up nmake
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up kColorPicker
      run: bash ./.github/scripts/setup_kColorPicker.sh

    - name: Set up kImageAnnotator
      run: bash ./.github/scripts/setup_kImageAnnotator.sh

    - name: Build
      run: bash ./.github/scripts/build_ksnip.sh

    - name: Download OpenSSL
      run: |
        curl -L "https://github.com/ksnip/dependencies/raw/master/windows/openSSL.zip" --output openssl.zip
        7z x openssl.zip -o"${{ env.OPENSSL_DIR }}"

    - name: Download CompileRuntime
      run: |
        curl -L "https://github.com/ksnip/dependencies/raw/master/windows/compileRuntime.zip" --output compileruntime.zip
        7z x compileruntime.zip -o"${{ env.COMPILE_RUNTIME_DIR }}"

    - name: Package exe
      run: bash ./.github/scripts/windows/package_exe.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ksnip-windows.zip
        path: ksnip-*.zip

    - name: Delete existing release with same name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash ./.github/scripts/delete_release.sh

    - name: Upload Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ksnip-${{ env.VERSION }}-windows.zip
        asset_name: ksnip-${{ env.VERSION }}-windows.zip
        tag: ${{ env.RELEASE_TAG }}
        overwrite: true
        release_name: ${{ env.RELEASE_NAME }}
        body: ${{ env.UPLOADTOOL_BODY }}
        prerelease: ${{ env.IS_PRERELASE }}


  package-msi:
    if: ${{ github.event_name == 'push' }}
    runs-on: windows-latest
    needs: test-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up build variables
        run: bash ./.github/scripts/setup_build_variables.sh

      - name: Set up windows build variables
        run: bash ./.github/scripts/windows/setup_windows_build_variables.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          install-deps: 'true'
          arch: 'win64_msvc2019_64'

      - name: Set up nmake
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up kColorPicker
        run: bash ./.github/scripts/setup_kColorPicker.sh

      - name: Set up kImageAnnotator
        run: bash ./.github/scripts/setup_kImageAnnotator.sh

      - name: Download OpenSSL
        run: |
          curl -L "https://github.com/ksnip/dependencies/raw/master/windows/openSSL.zip" --output openssl.zip
          7z x openssl.zip -o"${{ env.OPENSSL_DIR }}"

      - name: Download CompileRuntime
        run: |
          curl -L "https://github.com/ksnip/dependencies/raw/master/windows/compileRuntime.zip" --output compileruntime.zip
          7z x compileruntime.zip -o"${{ env.COMPILE_RUNTIME_DIR }}"

      - name: Build
        run: bash ./.github/scripts/build_ksnip.sh

      - name: Package msi
        run: bash ./.github/scripts/windows/msi/package_msi.sh

      - name: Sign msi
        env:
          MICROSOFT_CERT_PFX: ${{ secrets.MICROSOFT_CERT_PFX }}
          MICROSOFT_CERT_PFX_PASS: ${{ secrets.MICROSOFT_CERT_PFX_PASS }}
        run: powershell ./.github/scripts/windows/msi/sign_msi_package.ps1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ksnip-windows.msi
          path: ksnip-*.msi

      - name: Delete existing release with same name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./.github/scripts/delete_release.sh

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ksnip-${{ env.VERSION }}.msi
          asset_name: ksnip-${{ env.VERSION }}.msi
          tag: ${{ env.RELEASE_TAG }}
          overwrite: true
          release_name: ${{ env.RELEASE_NAME }}
          body: ${{ env.UPLOADTOOL_BODY }}
          prerelease: ${{ env.IS_PRERELASE }}
